package com.instaclone.instaclone.model.enums;

public enum Category {
    NATURE, SPORT, TRAVEL, TECHNOLOGY, FASHION, FOOD_DRINK, ANIMALS, CLUBBING, URBAN_LIFE, ART, SELFIE,
    HISTORY_RELIGION, EDUCATION, HEALTH_BEAUTY, MEME, OTHER
}
